# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53ba267793c1aaf9577502319c5bcd34d3211b5c7c26312fbbc00a4e10548bad6e352d0d2120321ec23d8ad2ea2a977dfdfff42c348dcab3850b4d586b2c0782

test:
  secret_key_base: b6d1d86075bdbcb19fb427ba8f32a4d703f3ea24a3fa77fafeae602117dbffe822651bfb69bbbe45ab100a335246e58de6506b53b41582c5422eb7535d6576a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
